### ISSUE TITLE
visorserialclient0 is using irq 0, the timer IRQ

### ISSUE THREAD

**Issue by prarit** [BenRomer/unisys#26]
[    4.130043] visorserialclient0 at MMIO 0x1 (irq = 0, base_baud = 921600) is a visorserial

The above doesn't look right.  IRQ 0 is the timer IRQ and in _most_ cases it is solely used by the timer.  Can anyone confirm that visorserialclient0 should really be using IRQ 0?  Typically serial drivers use IRQs 3 & 4 ...

**Comment by davidker** [comment]
A quick glance at the code, and I think visorserial is just polling, so I’m pretty sure the IRQ is incorrect.

David
