### ISSUE TITLE
rx_count can exceed the napi budget amount resulting in a WARN_ON

### ISSUE THREAD

**Issue by davidker** [BenRomer/unisys#29]
During internal testing noticed a WARN_ON when the rx_count from the poll processed more data than the napi_budget allowed.

**Comment by davidker** [comment]
I believe this gets fixed with https://github.com/BenRomer/unisys/commit/d077ea47ba48e10b1c3742452a1ce5d664582189

I'm wondering if we should pull this from later and put it in now, since we have actually hit this issue.

**Comment by BenRomer** [comment]
I pushed this patch up today to Greg.

**Comment by davidker** [comment]
Accepted into staging. Closing this issue.

https://git.kernel.org/cgit/linux/kernel/git/gregkh/staging.git/commit/drivers/staging/unisys/visornic/visornic_main.c?h=staging-testing&id=61dd330a284b7164eda3549ea3ec1bb53598a21e
