### ISSUE TITLE
XXX should 'inp_pfn + i' be a 64 bit type?

### ISSUE THREAD

**Issue by BenRomer** [BenRomer/unisys#30]
DanC's smatch run says: drivers/staging/unisys/include/iochannel.h:600 add_physinfo_entries() warn: XXX should 'inp_pfn + i' be a 64 bit type?

Needs a patch.

**Comment by davidker** [comment]
Sadly, I might agree with him but this might be more detailed than it should be because I believe the physinfo structure is shared across server/client. So if we just give it 64 in the guest it won't work.

**Comment by davidker** [comment]
Submitted to the upstream.

**Comment by davidker** [comment]
Commited at https://git.kernel.org/cgit/linux/kernel/git/gregkh/staging.git/commit/?h=staging-testing&id=785d43077f855ef710aa765273d3355efa7c82fe
