### ISSUE TITLE
visorchipset.c:2217 visorchipset_ioctl() warn: user controlled 'adjustment' cast to > postive rl = 's64min-s64max'

### ISSUE THREAD

**Issue by BenRomer** [BenRomer/unisys#32]
DanC's smatch run says:

> drivers/staging/unisys/visorbus/visorchipset.c:2217
> visorchipset_ioctl() warn: user controlled 'adjustment' cast to
> postive rl = 's64min-s64max'
> 
> This is because we read a s64 and pass it to a function as u64.

Needs a patch.

**Comment by davidker** [comment]
patch submitted to staging-next.

**Comment by davidker** [comment]
patch has been accepted.
